num1_str = input("Enter the first integer: ")
num1 = float(num1_str)
num2_str = input("Enter the second integer: ")
num2 = float(num2_str)
num3_str = input("Enter the third integer: ")
num3 = float(num3_str)
sum_of_numbers = (num1+num2+num3)
product_of_numbers = (num1*num2*num3)
average_of_numbers = ((num1+num2+num3)/3)
print(f"The sum of the numbers: {sum_of_numbers:.0f}")
print(f"The product of the numbers: {product_of_numbers:.0f}")
print("The average of the numbers: "  +str(average_of_numbers))